name: CI Build & Healthcheck

env:
  PYTHONPATH: ./docker/fastapi

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Build FastAPI container
        run: docker build -t fastapi-app ./docker/fastapi

      - name: Start services with Docker Compose
        run: docker compose up -d

      - name: Wait for FastAPI to be ready
        run: sleep 5

      - name: Healthcheck test
        run: curl -f http://localhost:8000/health

      - name: Shut down
        run: docker compose down