name: CI/CD Pipeline

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

jobs:
  build-test-lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/fastapi/requirements.txt

    - name: Run tests
      run: pytest
      env:
        PYTHONPATH: ./docker/fastapi

    - name: Lint (black)
      run: |
        python -m pip install --upgrade pip
        pip install black
        black .