name: Full CI Pipeline

on:
  push:
    branches: [main, dev, staging]
  pull_request:
    branches: [main, dev, staging]

env:
  PYTHONPATH: ./docker/fastapi

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r docker/fastapi/requirements.txt
        pip install pytest

    - name: Run tests
      run: pytest

    - name: Lint (black)
      run: |
        pip install black
        black .

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build FastAPI container
      run: docker build -t fastapi-app ./docker/fastapi

    - name: Start services with Docker Compose
      run: docker compose up -d

    - name: Show FastAPI logs
      run: docker logs $(docker ps -qf "name=web")
    
    - name: Wait for FastAPI to be ready
      run: |
        for i in {1..10}; do
          if curl -f http://localhost:8000/health; then
            echo "FastAPI is up!"
            break
          fi
          echo "Waiting for FastAPI to start..."
          sleep 3
        done

    - name: Healthcheck test
      run: curl -f http://localhost:8000/health

    - name: Shut down
      run: docker compose down